export const ALL_CODE_TYPES = {
  COUNTRY: "COUNTRY",
  FILM_TYPE: "FILM_TYPE",
  RANK: "RANK",
  GENRE: "GENRE",
  VERSION: "VERSION",
  YEAR: "YEAR",
  SORT: "SORT",
  GENDER: "GENDER",
  ROLE: "ROLE",
  USER_STATUS: "USER_STATUS",
  FILM_STATUS: "FILM_STATUS",
} as const;
